import { chromium } from 'playwright'
const OUT = process.argv[2]
const b = await chromium.launch({ channel: 'chrome' })
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } })
const errs = []
p.on('pageerror', e => errs.push(String(e).slice(0,180)))
await p.goto('http://localhost:5173/', { waitUntil: 'networkidle', timeout: 90000 })
await p.waitForTimeout(5000)
await p.screenshot({ path: `${OUT}/r-overture.png` })
await p.getByRole('button', { name: 'Open the workspace' }).click()
await p.waitForTimeout(3500)
await p.screenshot({ path: `${OUT}/r-priority.png` })
await p.getByRole('button', { name: /^Heat/ }).click()
await p.waitForTimeout(3000)
await p.screenshot({ path: `${OUT}/r-heat.png` })
await p.getByRole('button', { name: /^Canopy/ }).click()
await p.waitForTimeout(3000)
await p.screenshot({ path: `${OUT}/r-canopy.png` })
console.log('errors:', errs.length ? [...new Set(errs)].slice(0,3) : 'none')
await b.close()
