import { chromium } from 'playwright'
const OUT = process.argv[2]
const b = await chromium.launch({ channel: 'chrome' })
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } })
await p.goto('http://localhost:5173/', { waitUntil: 'networkidle', timeout: 90000 })
await p.waitForTimeout(4500)
await p.getByRole('button', { name: 'Open the workspace' }).click()
await p.waitForTimeout(2500)
await p.getByRole('button', { name: /^People/ }).click()
await p.waitForTimeout(3000)
await p.screenshot({ path: `${OUT}/fix-people.png` })
await p.getByRole('button', { name: /^Heat/ }).click()
await p.waitForTimeout(3000)
await p.screenshot({ path: `${OUT}/fix-heat.png` })
await b.close()
console.log('ok')
